config/routes.rb
Creditflex::Application.routes.draw do

  resources :interests

  resources :dares

  resources :echos

  resources :badges do
	member do
		get 'assertion'
	end
  end

  resources :challenges do
    member do
	   get 'review'
	   get 'new_from_image'
	   get 'add_image'

	end
	   
	collection do 
		get 'add_image'
		get 'new_from_wish'
		get 'new_from_image'
		post 'icreate'
		end
	end

  resources :wishes do
	member do
		get 'show_challenge'
		get 'share_challenge'
		get 'echo'
		post 'echo'
		get 'confirm_echo'
		post 'confirm_echo'
		get 'tweet'
		post 'tweet'

	end
	collection do 
			get 'add_image'
		end
	end
  resources :comments

  mount Ckeditor::Engine => '/ckeditor'

  resources :responses do
        member do
            post 'new'
		end
	end
  get "sessions/new"
  get "logout" => "sessions#destroy", :as => "logout"
  get "signup" => "users#new", :as => "signup"
  
  resources :users
  resources :sessions

  resources :students

  resources :projects do
        member do
			end
	end
  resources :resources

  resources :users do
			collection do
			
			get 'add_response'
			post 'add_response'
			end	
			
	end		
  resources :teachers 

  resources :portfolios 
		
  resources :requests do
        member do
            post 'new'
			post 'show'
			get 'add_response'
			post 'add_response'
			get 'up_vote'
			post 'up_vote'
			end
		collection do
			
			get 'add_response'
			post 'add_response'
			end	
	end

  resources :proposals do
  collection do 
		get 'add_image'
		get 'new_from_wish'
		get 'new_from_challenge'
		end
  end

  resources :proposal_types

  resources :proposal_statuses

  resources :subjects

  resources :courses do
        member do
            post 'new'
			end
		collection do
			get 'by_subject'
			end	
	end

     match 'lycee' => 'lycee#index'
	 match 'lycee/credits' => 'lycee#credits'
	 match 'lycee/rigor' => 'lycee#rigor'
	 match 'signup_now' => 'users#new'
	 match 'login' => 'users#new'

   root :to => 'wishes#index'

end

app/models/wish.rb
class Wish < ActiveRecord::Base
  attr_accessible :user_id, :wish
  belongs_to :user
  belongs_to :challenge
  has_many :echoes

public
def self.wish_stream

  @wishes = Wish.order("created_at desc").limit(100)
  @echoes = Echo.order("created_at desc").limit(50).map do |echo|
	OpenStruct.new(created_at: echo.created_at, wish: echo.wish.wish, user: echo.wish.user, echoed_by: echo.user, echo_count: echo.wish.echoes.count)
  end
  
  # @rewishes = @echoes.collect{|x| x.wish} + @wishes
  # @rewishes = @rewishes.sort_by { |obj| obj.created_at }.reverse!
  
  ( @echoes + @wishes ).sort_by(&:created_at).reverse!

end

def echo_count
	echoes.count
end

end

app/controllers/wishes_controller.rb
class WishesController < ApplicationController
load_and_authorize_resource 
# :except => [:index, :show]

  # GET /wishes
  # GET /wishes.json
  def index
	@projects = Project.all
	@wish = Wish.new
	@wish.user_id = current_user.try(:id)

	@wishes = Wish.wish_stream
	
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @wishes }
    end
  end

  def wish_stream
	@wishes = Wish.wish_stream
	logger.debug "Wishes: #{ @wishes.inspect }"
    respond_to do |format|
      format.html { logger.debug "html!" }
	  format.js { logger.debug "js!" }
      format.json { render json: @wishes }
    end
	
	
  end

    def confirm_echo
      @wish = Wish.find( params[:id] )
      respond_to do |format|
        format.html 
        format.js
    end
  end

  def echo
  @echo = Echo.new
  @echo.wish_id = params[:id]
  @echo.user_id = current_user.id
   respond_to do |format|
      if @echo.save
	    @wishes = Wish.wish_stream
		format.js 
        format.json { render json: @echo, status: :created, location: @echo }
      else
        format.html { render action: "wishes" }
        format.json { render json: @echo.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def show_challenge()
	#logger.debug "Params[:id]: #{ params[:id] }"
	#logger.debug "Params[]: #{ params.inspect }"
	@wish = Wish.find( params[:id] )
	@challenge = @wish.challenge
    @challenge = @wish.challenge
	@user = @wish.user

     respond_to do |format|
       format.html  
       format.js 
     end
  end

  def share_challenge()
	@wish = Wish.find( params[:id] )
	@user = @wish.user
	@dare = Dare.new
	@dare.wish_id = @wish.id
     respond_to do |format|
       format.html  
       format.js 
     end
  end

  def tweet()
  @wish = Wish.find( params[:id] )
  logger.debug "#{ @wish.username} challenged #{ params[:challengee]}to #{ @wish.wish} with Ohio Credit Flexibility. http://creditflexibility.org" 
  #Twitter.update("#{ @wish.user.user} challenges you to #{ @wish.wish} with Ohio Credit Flexibility.")

    #rescue Twitter::Error
    #  flash[:notice] = "ERROR with Twitter"
    #  redirect_to(:action => 'show')
     # return
     respond_to do |format|
       format.html  
       format.js 
     end
  end

  # GET /wishes/1
  # GET /wishes/1.json
  def show
    @wish = Wish.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @wish }
    end
  end
  
    def add_image
      @wish = Wish.find( params[:id] )
      respond_to do |format|
        format.html 
        format.js
    end
  end

  # GET /wishes/new
  # GET /wishes/new.json
  def new
    @wish = Wish.new
	@wish.user_id = current_user.id
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @wish }
    end
  end

  # GET /wishes/1/edit
  def edit
    @wish = Wish.find(params[:id])
  end

  # POST /wishes
  # POST /wishes.json
  def create
    @wish = Wish.new(params[:wish])
    @wish.user_id = current_user.id
    respond_to do |format|
      if @wish.save
        format.html { redirect_to @wish, notice: 'Wish was successfully created.' }
        format.json { render json: @wish, status: :created, location: @wish }
      else
        format.html { render action: "new" }
        format.json { render json: @wish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /wishes/1
  # PUT /wishes/1.json
  def update
    @wish = Wish.find(params[:id])

    respond_to do |format|
      if @wish.update_attributes(params[:wish])
        format.html { redirect_to @wish, notice: 'Wish was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @wish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wishes/1
  # DELETE /wishes/1.json
  def destroy
    @wish = Wish.find(params[:id])
    @wish.destroy

    respond_to do |format|
      format.html { redirect_to wishes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/wishes_helper.rb
module WishesHelper
end

app/views/wishes/_confirm_echo.html.erb
  <div class="stream-item">
  <div class="left-user">
  <%= image_tag(@wish.user.avatar.url, :class => 'avatar-small') if @wish.user.avatar? %>&nbsp;
  </div>
<div class="wish">
    <div class="wish-header"><span class="wisher">
    <%= @wish.user.username if @wish.user %>
	</span></div>
	<div class="wish-body">
	<%= @wish.wish %> 
</div>
</div>
</div>
<%=  (link_to 'Echo this wish?', echo_wish_path(:id), :id => "echo-button", remote: true )  %><%= image_tag('echo1.png', :class => 'echo-teeny')  %>

app/views/wishes/_echo.html.erb
  <div class="stream-item">
  <div class="left-user">
  <%= image_tag(@wish.user.avatar.url, :class => 'avatar-small') if @wish.user.avatar? %>&nbsp;
  </div>
<div class="wish">
    <div class="wish-header"><span class="wisher">
    <%= @wish.user.username if @wish.user %>
	</span></div>
	<div class="wish-body">
	<%= @wish.wish %> 
</div>
</div>
</div>
<%=  (link_to 'Echo this wish?', echo_wish_path(:id), remote: true )  %><%= image_tag('echo1.png', :class => 'echo-teeny')  %>

app/views/wishes/_form.html.erb
<%= form_for(@wish) do |f| %>
  <% if @wish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wish.errors.count, "error") %> prohibited this wish from being saved:</h2>

      <ul>
      <% @wish.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :wish %><br />
    <%= f.text_field :wish %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wishes/_form1.html.erb
<%= form_for(@wish) do |f| %>
  <% if @wish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wish.errors.count, "error") %> prohibited this wish from being saved:</h2>

      <ul>
      <% @wish.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="new-wish">

    <%= f.text_area :wish, :size => "30x4", :placeholder => "I'd learn..." %>
  </div>
  <div class="field-hidden">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="flex-button">

    <%= f.submit "Wish!" %>

  </div>
<% end %>

app/views/wishes/_share.html.erb
<style type="text/css" media="screen">

 .twitter-share-button a {

    display: block;

    padding: 2px 5px 2px 20px;

    background: url('https://twitter.com/favicons/favicon.ico') 1px center no-repeat;

    border: 1px solid #ccc;

  }

</style>
<div class="fb-send" data-href="http://example.com" data-font="arial"></div>
<div>

<%= form_for(@dare, :remote => true) do |f| %>
  <% if @dare.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dare.errors.count, "error") %> prohibited this wish from being saved:</h2>

      <ul>
      <% @dare.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<br />
Who would you challenge?
  <div class="new-wish">

    <%= f.text_area :challengee_twitid, :size => "30x1", :placeholder => "Twitter handle of friend" %>
  </div>
  <div class="field-hidden">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
    <div class="field-hidden">
    <%= f.label :wish_id %><br />
    <%= f.number_field :wish_id %>
  </div>
  <div class="flex-button">

    <%= f.submit "Challenge" %>

  </div>
<% end %>

<%# link_to("Tweet", tweet_wish_path, :class=>"twitter-share-button") %>

app/views/wishes/_wish.html.erb
  <div class="stream-item">
  <div class="left-user">
  <%= image_tag(@wish.user.avatar.url, :class => 'avatar-small') if @wish.user.avatar? %>&nbsp;
  </div>
<div class="wish">
    <div class="wish-header"><span class="wisher">
    <%= @wish.user.username if @wish.user %>
	</span></div>
	<div class="wish-body">
	<%= @wish.wish %> 
</div>
</div>
</div>
<div class="echo-footer">
<div id="close">
<span id="close" class="g_button3" >Cancel</span></div>
<%= link_to echo_wish_path(@wish.id), remote: true, :class => "b_button3"  do %>
	    Echo <%= image_tag('echo2.gif', :class => 'echo-teeny')  %>
		<% end %>

</div>


<script>

$(document).ready(function (){
  
  $('#close').click(function(){
   $('div#modal-container2').hide("slow");
   //$('div#echo-popup').html("");
  });

});

</script>

app/views/wishes/_wish_stream.html.erb
<div class="stream">


<% @wishes.each do |wish| %>
  <div class="stream-item">
  <div class="left-user">
  <%= image_tag(wish.user.avatar.url, :class => 'avatar-small') if wish.user.avatar? %>&nbsp;
  </div>
  <div class="wish">
    <div class="wish-header"></div>
	<div class="wish-body">
	<%= wish.wish %>  
    <% if (wish.echo_count > 0 ) %>
	<span class="echo-count"><%= wish.echo_count  %><%= " echo".pluralize(wish.echo_count ) %></span>
	<% end %>
	<div class="wish-admin">
	User: <%= wish.user_id %>
	
	</div>
	</div>
	<div class="wish-footer">
	<span class="wisher">
    <%= wish.user.username if wish.user %>
	</span>
	<%=  (link_to 'View Challenge', show_challenge_wish_path(wish), remote: true ) if wish.try(:challenge_id) %>
	<%= link_to confirm_echo_wish_path(wish), remote: true do %>
	    Echo <%= image_tag('echo1.png', :class => 'echo-teeny')  %>
		<% end %>
	<%=  (link_to 'Challenge a friend', share_challenge_wish_path(wish), remote: true )  %>
	</div>
	</div></div>
<% end %>

</div>

app/views/wishes/add_image.js.erb
// $.get("add_image", function(data) {
$('div#upload-dialogue').html('<%=j render("image_form") %>');
// });
 
    $('div#modal-container5').show();

app/views/wishes/edit.html.erb
<h1>Editing wish</h1>

<%= render 'form' %>

<%= link_to 'Show', @wish %> |
<%= link_to 'Back', wishes_path %>

app/views/wishes/index.html.erb
<div class="main">
<h3>&nbsp;Get High School Credit for what <i>you</i> want to do.</h3>


<div id="featured" class="left-box" >
<p >Take a trip, get an internship, do research, start a business, take a class outside school, go to iTunesU, you name it!
</p>
<i>Your</i> school grants the credit.<br /> 
<%= image_tag("OpenBadges_Insignia_WeIssue_Banner.png", :class => "open_badge") %>
<%# image_tag("apprentice4.jpg", :id => "main-pic", :alt => "cc Sorceress' Apprentice by Sheryl Westleigh", :title => "cc Sorceress' Apprentice by Sheryl Westleigh") %>
<%# image_tag("dragon.jpg", :id => "main-pic", :alt => "CC Julian Lee") %>
<%# image_tag("cafe.jpg", :id => "main-pic") %>
<p>Teachers, students, community members, let's work together here to re-imagine school.</p>
</div>
<div class="col-right">
<div class="center-top">
<h2>What would you master?</h2>
...for credit in school?
</div>










<div id="content-wishes2" class="wrapper">
<div id="column-1">
<div id="wish-list">
<div class="stream_header">

<div class="new-wish">
<%= render 'form1' %>


</div>
</div>

<div id="wish-stream">
<%= render 'wish_stream' %>
</div>

<div class="stream_footer">
<%= link_to 'New Wish', new_wish_path %>
</div>
</div>
</div>


</div>



</div>


<div id="lower-left1">




</div>


<div id="feature_text2">
<div id="main_text">
<div id="intro">
</div>

</div>
<iframe width="200" height="150" src="http://www.youtube.com/embed/yAg1pNu2eWY" frameborder="0" allowfullscreen></iframe>
  <p class="learn_more">
      <%= link_to("Explore", lycee_path) %> &nbsp; &nbsp; &nbsp;
    <%= link_to("Learn more", resources_path) %>.
  </p>
  <div id="fb">
    <%= link_to("Students at Reynoldsburg explain in a cool infographic!", "../infographic.png") %> <p style="display:none" class="not_ohio"><a href="http://peerbackers.com/projects/10000-creit-flex-students-by-2013" target="blank">Help spread the word and get 10,000 students on CreditFlex</a> Not in Ohio? Credit Flexibility may be coming to your state!
  </p>
  </div>
<div id="caption">
</div>


<div id="projects1">
 <div class="clearfix" id="projects_bar">
<div class="t_band">
 <div class="spacer12" ></div>
 <h3>Who's Used Credit Flex?</h3></div>
 (I already learned...)
 <div class="spacer14" >
 <%=link_to("Tell us about your CF project", new_project_path, :id => "add_project", :class => "add_button4") %>
 </div>
<% @projects[0..3].each do |project| %>
<div id="projects_item">
	<div class="item_desc3">
		
		<b><%= raw(truncate(project.title, :length => 140, :separator => ' ')) %> </b>
		<%# image_tag( project.projekt.url.to_s, :class => "projekt") if project.projekt? %>
		<p>&nbsp;<%= raw(truncate(project.summary, :length => 100, :separator => ' ')) %> <%= link_to("more", project) %></p>
	</div>
</div>
<% end %>
</div>
<div class="more1" >
<%= link_to("More", projects_path, ) %>
<%# link_to(image_tag("right_arrow.png", :class => "right_arrow"), projects_path, ) %>
</div>

<br /><%=link_to("Tell us about your CF project", new_project_path, :id => "add_project", :class => "add_button3") %>
</div>


</div>


</div>






<div id="modal-container" class="modal-container">
<div id="challenge-popup">
<div id="modal-header">
<div id="modal-close"><span id="modal-close">X</span></div>
<div class="modal-title"> Challenge: </div>
<div id="challenge-title">Title</div>
</div>
<div id="badge" class="small-badge">

</div>
<div id="modal-body" class="modal-body">

</div>
</div>
</div>

<div id="modal-container2" class="modal-container">
<div id="echo-popup">
<div id="modal-header">
<div id="modal-close"><span id="modal-close2">X</span></div>
<div class="modal-title"> </div>
<div id="challenge-title">Title</div>
</div>
<div id="modal-body2" class="modal-body">

</div>
</div>
</div>

<script>

$(document).ready(function (){
    
  $('#modal-close').hover(function(){
    $('span#modal-close').toggleClass('modal-hover');
  });

  $('#modal-close').click(function(){
    $('div#modal-container').hide("slow");
  });


  $('#modal-close2').hover(function(){
    $('span#modal-close2').toggleClass('modal-hover');
  });
  
  $('#modal-close2').click(function(){
    $('div#modal-container2').hide("slow");
  });
  
  $('#close').click(function(){
    $('div#modal-container2').hide("slow");
  });

  $('a#echo-button').click(function(){
   alert("Bing");
   $('div#modal-container2').hide("slow");
  });
});
</script> 
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
</script>

app/views/wishes/new.html.erb
<h1>What would you learn for credit?</h1>

<%= render 'form' %>

<%= link_to 'Back', wishes_path %>

app/views/wishes/notecho.js.erb
 $('div#modal-body').html('yep');
  $('div#challenge-title').html('Echo this Wish?');
  $('div#modal-container').show();

app/views/wishes/show.html.erb
<div class="content_course_outer">
<div class="content_course_inner">
<p id="notice"><%= notice %></p>



  <b>You want to learn:</b><br />
  <div id="moz-cred">
  <%= image_tag("we_issue.png", :id => "moz-cred1", :alt => "Mozilla Issuer Insignia", :title => "Mozilla Badge Issuer Insignia") %>
</div>
  <div class="wish_title"><%= @wish.wish %></div>
<div id="upload-image">
<% if @wish.challenge_id.nil? || @wish.challenge.challengepic.nil? %>  
Add an image for your challenge
<% else %>
<%= "Your pic here" %>
<% end %>
</div>
<% if @wish.challenge_id.nil? %>
<div id="challenge_options">
<p>Well, don't just sit there wishing...</p>



<%= link_to("Start designing your challenge.", new_from_wish_challenges_path(:wish => @wish),  :class => "b_button") %>
<p>
<%= link_to("I found a badge I'd like to earn and get credit for.", new_badge_path, :id => "add_badge", :class => "b_button") %>
</p>
<%= link_to("Not yet. Let's see more of what others are doing.", lycee_path, :id => "add_project", :class => "b_button2") %>
</div>
<% else %>
<%= link_to("View your challenge.", challenge_path(:id => @wish.challenge_id),  :class => "b_button") %>

<% end %>
</div><div>
<%= link_to 'Edit', edit_wish_path(@wish) %> |
<%= link_to 'Back', wishes_path %>
<%= @wish.user.avatar? %>
</div>

<div id="modal-container5" class="modal-container5">
<div id="upload-dialogue" class="uploader-popup">


</div>
</div>

<script>

$(document).ready(function (){


$('div#upload-image').click(function(){

  //$.get('/challenges/new_from_wish.js');
  //$.get('<%=j new_from_wish_challenges_path(:wish => @wish) %>');

//   $('div#modal-container5').show();
//    .done(function(data) {
// $('div#upload-dialogue').html(data)
// });
   
   
  $('div#image-upload').html($.get('<%=j add_image_wishes_path(:id => @wish.id, :remote => true ) %>')) 
//   $('div#image-upload').html($.get("add_image"))
});

    $('div#upload-image').hover(function(){
   $('div#upload-image').toggleClass('show-welcome-hover');
  });
});
</script>

app/views/wishes/wish_stream.html.erb
<div class="stream">


<% @wishes.each do |wish| %>
  <div class="stream-item">
  <div class="left-user">
  <%= image_tag(wish.user.avatar.url, :class => 'avatar-small') if wish.user.avatar? %>&nbsp;
  </div>
  <div class="wish">
    <div class="wish-header"><span class="wisher">
    <%= wish.user.username if wish.user %>
	</span></div>
	<div class="wish-body">
	<%= wish.wish %> 
    <% if (wish.echoes.count > 0 ) %>
	<span class="echo-count"><%= wish.echoes.count %><%= " echo".pluralize(wish.echoes.count) %></span>
	<% end %>
	<div class="wish-admin">
	User: <%= wish.user_id %>
    <%= link_to 'Show', wish %>
    <%= link_to 'Edit', edit_wish_path(wish) %>
    <%= link_to 'Destroy', wish, method: :delete, data: { confirm: 'Are you sure?' } %>
	</div>
	</div>
	<div class="wish-footer">
	
	<%=  (link_to 'View Challenge', show_challenge_wish_path(wish), remote: true ) if wish.try(:challenge_id) %>
	<%= link_to confirm_echo_wish_path(wish), remote: true do %>
	    Echo <%= image_tag('echo1.png', :class => 'echo-teeny')  %>
		<% end %>
	<%=  (link_to 'Challenge a friend', share_challenge_wish_path(wish), remote: true )  %>
	</div>
	</div></div>
<% end %>

</div>