config/routes.rb
Creditflex::Application.routes.draw do

  resources :interests

  resources :dares

  resources :echos

  resources :badges do
	member do
		get 'assertion'
	end
  end

  resources :challenges do
    member do
	   get 'review'
	   get 'new_from_image'
	   get 'add_image'

	end
	   
	collection do 
		get 'add_image'
		get 'new_from_wish'
		get 'new_from_image'
		post 'icreate'
		end
	end

  resources :wishes do
	member do
		get 'show_challenge'
		get 'share_challenge'
		get 'echo'
		post 'echo'
		get 'confirm_echo'
		post 'confirm_echo'
		get 'tweet'
		post 'tweet'

	end
	collection do 
			get 'add_image'
		end
	end
  resources :comments

  mount Ckeditor::Engine => '/ckeditor'

  resources :responses do
        member do
            post 'new'
		end
	end
  get "sessions/new"
  get "logout" => "sessions#destroy", :as => "logout"
  get "signup" => "users#new", :as => "signup"
  
  resources :users
  resources :sessions

  resources :students

  resources :projects do
        member do
			end
	end
  resources :resources

  resources :users do
			collection do
			
			get 'add_response'
			post 'add_response'
			end	
			
	end		
  resources :teachers 

  resources :portfolios 
		
  resources :requests do
        member do
            post 'new'
			post 'show'
			get 'add_response'
			post 'add_response'
			get 'up_vote'
			post 'up_vote'
			end
		collection do
			
			get 'add_response'
			post 'add_response'
			end	
	end

  resources :proposals do
  collection do 
		get 'add_image'
		get 'new_from_wish'
		get 'new_from_challenge'
		end
  end

  resources :proposal_types

  resources :proposal_statuses

  resources :subjects

  resources :courses do
        member do
            post 'new'
			end
		collection do
			get 'by_subject'
			end	
	end

     match 'lycee' => 'lycee#index'
	 match 'lycee/credits' => 'lycee#credits'
	 match 'lycee/rigor' => 'lycee#rigor'
	 match 'signup_now' => 'users#new'
	 match 'login' => 'users#new'

   root :to => 'wishes#index'

end

app/controllers/lycee_controller.rb
class LyceeController < ApplicationController

   def index
    @projects= Project.all
    @requests = Request.all
    @proposals = Proposal.all
	@courses = Course.all
	@teachers = Teacher.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @proposals }
    end
  end
end

app/helpers/lycee_helper.rb
module LyceeHelper
end

app/views/lycee/credits.html.erb
<h1>Who Helped Here?</h1>


<div id="featured">

<%= image_tag("team.jpg", {:height => 320}) %>
<div id="feature_text">
<div id="main_text">
<div id="intro">
Giving students more options for rigorous, relevant learning is what we're all about here. <p>We couldn't have got it off the ground but on the shoulders of others!</p></div>



</div>
<div id="caption"><br /><br />

</div>
</div>
</div>




<div id="projects">
 <div class="clearfix" id="projects_bar">
<div class="t_band">
<%= image_tag("penguin.png", :class => "penguin") %>
 <h3>Images</h3></div>

Most of the wonderful iconic images here are from the fantastic contributors to <%=  link_to("OpenClipart.org", 'http://openclipart.org' )  %>

<p>The shot of the student robotics competion on the Learn More page  <a href="http://www.flickr.com/photos/nics_events/3416252377/">comes from</a> Flickr user Nic. </p>
<p>The photo of the USN Seals in training comes from <%= link_to('Rennett Stowe on Flickr', "http://www.flickr.com/photos/tomsaint/2705089414/") %>.
<p>The pic of students at a counter on the Learn More page was made available via Flickr by Tulane University:<%= link_to('counter pic', "http://www.flickr.com/photos/tulanesally/5887771701/sizes/m/in/photostream/") %></p>
<p>The above image is <%= link_to('from fotopedia', 'http://www.fotopedia.com/items/flickr-5486339493' ) %>, taken from wikipedia content.</div>
<br />
</div>

<div id="requests">
 <div class="clearfix" id="projects_bar">
<div class="t_band">
<%= image_tag("penguin.png", :class => "penguin") %>
 <h3>Software</h3></div>

This site is build on the immense work done by the <%=  link_to("Ruby", 'http://ruby-lang.org' )  %> and <%=  link_to("RAILS", 'http://rubyonrails.org' )  %> Communities.</div>

Including the developers and contributors to these gems and others generously made available at <%=  link_to("Rubygems.org", 'http://rubygems.org' )  %>:
<ul>
<li> 'carrierwave'
#<li> 'rmagick'
<li> 'mini_magick'
<li> 'fog'

<li> "ckeditor", "3.7.0.rc2"
<li> 'rinku'

<li> 'make_voteable'


  <li> 'sass-rails',   '~> 3.2.3'
  <li> 'coffee-rails', '~> 3.2.1'
  <li> 'uglifier', '>= 1.0.3'


<li> 'jquery-rails', '>= 2.0.1'
<li> 'sorcery'
<li> 'cancan'
<li> 'fog'
<li> 'pry'
	#<li> 'eventmachine', "1.0.0.beta.4.1"
	#<li> 'thin'
	<li> 'sqlite3'

    

  <li> 'turn'



 <li> 'pg'

</ul>


</div>
<div class="clear"> .</div>

app/views/lycee/index.html.erb
<%= image_tag("preview.png", :id => "preview" ) %>


<h1>Who's Using Credit Flexibility?</h1>


<div id="featured">

<%= image_tag("cafe.jpg", {:height => 360}) %>
<div id="feature_text">
<div id="main_text">
<div id="intro">
Credit Flexibility is the new way to get credit toward high school graduation by <i>doing almost anything</i>.</div>
<p >Take a trip, get an internship, do research, start a business, take a class outside school, go to iTunesU, you name it!
</p>
</div>

<p class="learn_more">
<a href="http://www.youtube.com/watch?v=yAg1pNu2eWY" target="blank">See the CF video</a>. &nbsp; &nbsp;<%= link_to("Learn more", resources_path) %>.</p><div id="fb">
<a href="infographic.png" >Students at Reynoldsburg explain in a cool infographic!</a> <p style = "display:none" class="not_ohio"><a href="http://peerbackers.com/projects/10000-creit-flex-students-by-2013" target="blank">Help spread the word and get 10,000 students on CreditFlex</a> Not in Ohio? Credit Flexibility may be coming to your state!</p></div>
<div id="caption"><br /><br />
Want your project featured here? <br/>Send us a pic and description.
</div>
</div>
</div>




<div id="projects">
 <div class="clearfix" id="projects_bar">
<div class="t_band">
<%= image_tag("presentation.png", :class => "penguin") %>
 <h3>Share Your Credit Flex Project</h3></div>
<% @projects[0..3].each do |project| %>
<div id="projects_item">
	<div class="item_desc">
		
		<b><%= raw(truncate(project.title, :length => 140, :separator => ' ')) %> </b>
		<%= image_tag( project.projekt.url.to_s, :class => "projekt") if project.projekt? %>
		<p><b>I'm:</b>&nbsp;<%= raw(truncate(project.summary, :length => 200, :separator => ' ')) %> <%= link_to("more", project) %></p>
	</div>
</div>
<% end %>
<%= link_to(image_tag("right_arrow.png", :class => "right_arrow"), projects_path, ) %>
</div>
<br /><%=link_to("Tell us about your CF project", new_project_path, :id => "add_project", :class => "add_button") %>
</div>



<div id="requests">
 <div class="clearfix" id="requests_bar">
<div class="c_band">
<%= image_tag("guitar_hero.png", :class => "penguin") %>
 <h3>Who's Looking for Help?<br />Ask here about credit flex options.</h3></div>
<% @requests[0..3].each do |request| %>
<div id="requests_item">
	<div class="item_desc">
	<%# image_tag( request.user.avatar.url.to_s, :class => "t_avatar") if request.user.avatar? %>
	<%# image_tag( "thumbup30.png" ) %>
		<b><%= request.topic %></b><br /><br />
		<b>Goals: </b> <%= truncate(request.goals, :length => 140, :separator => ' ') %> <%= link_to("more", request) %><br />
		<p><b>Help needed:</b> <%= truncate(request.help_needed, :length => 140, :separator => ' ') %> <%= link_to("more", request) %></p>
	</div>
</div>
<% end %>
<%= link_to(image_tag("right_arrow.png", :class => "right_arrow"), requests_path, ) %>

</div>
<br /><%=button_to("Ask about credit flex", new_request_path, :id => "add_request", :class => "add_button") %> 
</div>


<div id="lycee">
 <div class="clearfix" id="courses_bar">
<div class="c_band">
<%= image_tag("zt180_ecosystems.png", :class => "penguin") %>

<h3>Want a Course?<br /><br />Approved online or non-traditional courses</h3></div> 
<% @courses[0..3].each do |course| %>
<div id="courses_item">
<div class="item_desc">
    <span class="item_title"><%= course.title %></span><br />
    <%= truncate(course.description, :length => 140, :separator => ' ') %> <%= link_to("more", course) %>
	<p><b>Subject: </b> <%= course.subject.name %></p>
	<%= if course.hqt == true then link_to(image_tag("penguin_thumb_up.png", :class => "hqt_needed"), course)  else link_to(image_tag("penguin_question.png", :class => "hqt_needed"), course) end %>
    <p><b>Notes: </b> <%= truncate(course.notes, :length => 50, :separator => ' ') %> <%= link_to("more", course) %>

<br />
    <b><%= link_to("Course link", course.curriculum_url) %></b>
	</div>
</div>
<% end %>
<%= link_to(image_tag("right_arrow.png", :class => "right_arrow"), courses_path) %>
</div>
<%=button_to("Add an approved course", new_course_path, :id => "add_course", :class => "add_button2") %>
</div>

<div id="teachers">
<div class="t_band">
<%= image_tag("penguinredcross.png", :id => "penguin") %>
<h3>Who's Available to Help?<br /><br />Teachers </h3>
</div>
<div class="clearfix"  id="teachers_bar">
<% @teachers[0..3].each do |teacher| %>
<div id="teachers_item">
<div class="item_desc">
    <b><%= "#{teacher.title} " if teacher.title? %><%= teacher.name %></b><%= image_tag( teacher.avatar.url.to_s, :class => "t_avatar") if teacher.avatar? %><br />
    <%= truncate(teacher.bio, :length => 140, :separator => ' ') %> 
	<%= link_to("more", teacher) %>
	<p><b>Subject: </b> <%= teacher.subject %></p>
	</div>
</div>
<% end %>
<%= link_to(image_tag("right_arrow.png", :class => "right_arrow"), teachers_path) %>
</div>

 <div>
<%=link_to("Add teacher", new_teacher_path, :id => "add_mentor", :class => "add_button2") %>
</div>

</div>
<%=link_to("Credits", "/lycee/credits", :id => 'bottom_nav') %>

app/views/lycee/rigor.html.erb
<h1>Is CF Rigorous?</h1>


<div id="featured">

<%= image_tag("seals.jpg", {:height => 360}) %>
<div id="feature_text">
<div id="main_text">
<div id="intro">
 
<p>That's what we're here for.</p>
<div class="quote">One man is much the same as another,
... he is best who is trained in the severest school."
- Thucydides, "History of the Peloponnesian War" (431-404 B.C.)</div>

<p>We so trained in the day; we expect here to help students and teachers work toward the same.</p>
<p>Together, we can raise the bar across districts.</p>
<p>Will you consider contributing here to give students demanding and relevant options?</p></div>

<%= link_to("Learn more", resources_path) %>.</p><div id="fb">


</div>

</div>
</div>
<div class="clear" style="height:25px;"></div>
<div class="left">
<h2>Confidence</h2>
Step by step.<br />
Often one-on-one with adult, or with team.
</div>
<div class="right">
<h2>Competancy</h2>
Focus on mastery, not seat time.<br />
Mastery determined sometimes by assessment, other times by critical judgement of a Highly Qualified Teacher.
Potential for involvement with mentor/professional.
</div>
<div class="clear" style="height:25px;"></div>
<div id="orc">
<div class="titleb">In fact, the Legislature required Competancy and only Competancy</div>
The enabling legislation for Credit Flex was this:<br />
<h6>O.R.C. 3313.603(J)</h6> The state board of education, in consultation with the Ohio board of regents and the partnership for continued learning, <b>shall adopt a statewide plan implementing methods for students to earn units of high school credit based on a demonstration of subject area competency, instead of or in combination with completing hours of classroom instruction</b>. The state board shall adopt the plan not later than March 31, 2009, and commence phasing in the plan during the 2009-2010 school year. <b>The plan shall include a standard method for recording demonstrated proficiency on high school transcripts</b>. Each school district, community school, and chartered nonpublic school shall comply with the state board's plan adopted under this division and award units of high school credit in accordance with the plan. The state board may adopt existing methods for earning high school credit based on a demonstration of subject area competency as necessary prior to the 2009-2010 school year.
</div>

<div class="clear"> .</div>