config/routes.rb
Creditflex::Application.routes.draw do

  resources :interests

  resources :dares

  resources :echos

  resources :badges do
	member do
		get 'assertion'
	end
  end

  resources :challenges do
    member do
	   get 'review'
	   get 'new_from_image'
	   get 'add_image'

	end
	   
	collection do 
		get 'add_image'
		get 'new_from_wish'
		get 'new_from_image'
		post 'icreate'
		end
	end

  resources :wishes do
	member do
		get 'show_challenge'
		get 'share_challenge'
		get 'echo'
		post 'echo'
		get 'confirm_echo'
		post 'confirm_echo'
		get 'tweet'
		post 'tweet'

	end
	collection do 
			get 'add_image'
		end
	end
  resources :comments

  mount Ckeditor::Engine => '/ckeditor'

  resources :responses do
        member do
            post 'new'
		end
	end
  get "sessions/new"
  get "logout" => "sessions#destroy", :as => "logout"
  get "signup" => "users#new", :as => "signup"
  
  resources :users
  resources :sessions

  resources :students

  resources :projects do
        member do
			end
	end
  resources :resources

  resources :users do
			collection do
			
			get 'add_response'
			post 'add_response'
			end	
			
	end		
  resources :teachers 

  resources :portfolios 
		
  resources :requests do
        member do
            post 'new'
			post 'show'
			get 'add_response'
			post 'add_response'
			get 'up_vote'
			post 'up_vote'
			end
		collection do
			
			get 'add_response'
			post 'add_response'
			end	
	end

  resources :proposals do
  collection do 
		get 'add_image'
		get 'new_from_wish'
		get 'new_from_challenge'
		end
  end

  resources :proposal_types

  resources :proposal_statuses

  resources :subjects

  resources :courses do
        member do
            post 'new'
			end
		collection do
			get 'by_subject'
			end	
	end

     match 'lycee' => 'lycee#index'
	 match 'lycee/credits' => 'lycee#credits'
	 match 'lycee/rigor' => 'lycee#rigor'
	 match 'signup_now' => 'users#new'
	 match 'login' => 'users#new'

   root :to => 'wishes#index'

end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
belongs_to :user
delegate :username, :avatar, :avatar?, :email, :to => :user
#attr_accessible  :district, :school, :subject, :specialty, :bio, :notes, :first_name, :last_name, :title, :user_attributes

def name
 logger.debug "name #{self.first_name}"
 logger.debug "name #{self.last_name}"
 "#{self.first_name}" + " "+ "#{self.last_name}"
end

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all
logger.debug "@teachers: #{@teachers}"
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @teachers }
    end
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
    @teacher = Teacher.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @teacher }
    end
  end

  # GET /teachers/new
  # GET /teachers/new.json
  def new
    @teacher = Teacher.new
	
	#@user = User.new
	@teacher.user = current_user
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @teacher }
    end
  end

  # GET /teachers/1/edit
  def edit
    @teacher = Teacher.find(params[:id])
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(params[:teacher])

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render json: @teacher, status: :created, location: @teacher }
      else
        format.html { render action: "new" }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /teachers/1
  # PUT /teachers/1.json
  def update
    @teacher = Teacher.find(params[:id])

    respond_to do |format|
      if @teacher.update_attributes(params[:teacher])
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher = Teacher.find(params[:id])
    @teacher.destroy

    respond_to do |format|
      format.html { redirect_to teachers_url }
      format.json { head :ok }
    end
  end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.erb
<%= form_for(@teacher) do |f| %>
  <% if @teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% @teacher.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="bio">
    <%= f.label :bio %><br />
    <%= f.text_area :bio, :cols => 50 %>
  </div>
  <div class="field">
    <%= f.label 'User_name:' %>
    <b><%= current_user.username if current_user.present? %></b>
  </div>
  <div class="field">
    <%= f.label "First Name" %><br />
    <%= f.number_field :first_name %>
  </div>
    <div class="field">
    <%= f.label :last_name %><br />
    <%= f.number_field :last_name %>
  </div>
      <div class="field">
    <%= f.label :title %><br />
    <%= f.number_field :title %>
  </div>
  <div class="field">
    <%= f.label :district %><br />
    <%= f.text_field :district %>
  </div>
  <div class="field">
    <%= f.label :school %><br />
    <%= f.text_field :school %>
  </div>
  <div class="field">
    <%= f.label :subject %><br />
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :specialty %><br />
    <%= f.text_field :specialty %>
  </div>

  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_area :notes, :cols => 70, :rows => 9 %>
  </div>
  <div class="actions">
    <%= f.submit 'Send it'%>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<div class="content1">
<div class="form">
<%= image_tag("braintrust.png", :id => "penguin1") %>
<h1>Update Your Teacher/Mentor Profile</h1>
<h3>Thanks for helping students score individualized competancies.</h3>
<div class="clearfix"></div>
<%= render 'form' %>

<%= link_to 'Back', teachers_path %>
</div>
<div>
.
</div>
</div>

app/views/teachers/index.html.erb
<div class="content">
<h1>Mentors / Teachers</h1>


<div class="clearfix" id="nursery_bar">
<% @teachers.each do |teacher| %>
<div class='mentor'>

    
	<b><%= teacher.title %><%= teacher.first_name %>&nbsp;<%= teacher.last_name %></b><br />
	<div class='mentor_badge'>
	<%= image_tag( teacher.avatar.url.to_s, :class => "m_avatar") if teacher.avatar? %>
	<%= teacher.user.username %>
	</div>    
	District:<%= teacher.district %>, School: <%= teacher.school %>
    Subject, Specialty<%= teacher.subject %> <%= teacher.specialty %>

    <p><%= auto_link(truncate(teacher.bio, :length => 240, :separator => ' '), :all, :html => { :target => '_blank' } ) %>
</p>
    Notes: <%= teacher.notes %>
    <%= link_to 'More', teacher %>
	<% if can? :manage, teacher %>
    <%= link_to 'Edit', edit_teacher_path(teacher) %>
    <%= link_to 'Destroy', teacher, confirm: 'Are you sure?', method: :delete %>
	<% end %>
  </div>
<% end %>
</div>

<br />
<%=link_to("Add teacher or mentor", new_teacher_path, :class => "add_button3") %>
<div>

</div>
<div class="clear">
</div>

app/views/teachers/new.html.erb
<div class="content1">
<div class="form">
<%= image_tag("braintrust.png", :id => "penguin1") %>
<h1>Get Listed as Teacher/Mentor</h1>
<h3>Thanks for helping students score individualized competancies.</h3>
<div class="clearfix"></div>
<%= render 'form' %>

<%= link_to 'Back', teachers_path %>
</div>
<div>
.
</div>
</div>

app/views/teachers/show.html.erb
<div class='show_mentor'>
<p id="notice"><%= notice %></p>

	<div class='mentor_badge'>
	<%= image_tag( @teacher.avatar.url.to_s, :class => "m_avatar") if @teacher.avatar? %>
	<%= @teacher.user.username %>
	</div>  
<p>
	<b><%= @teacher.title %><%= @teacher.first_name %>&nbsp;<%= @teacher.last_name %></b><br />
</p>

<p>
  <b>District:</b>
  <%= @teacher.district %>
</p>

<p>
  <b>School:</b>
  <%= @teacher.school %>
</p>

<p>
  <b>Subject:</b>
  <%= @teacher.subject %>
</p>

<p>
  <b>Specialty:</b>
  <%= @teacher.specialty %>
</p>

<p>
  <b>Bio:</b>
  <%= @teacher.bio %>
</p>

<p>
  <b>Notes:</b>
  <%= @teacher.notes %>
</p>


<% if can? :manage, @teacher %>
<p>
  <b>User:</b>
  <%= @teacher.user_id %>
</p>
<%= link_to 'Edit', edit_teacher_path(@teacher) %> |
<%= link_to 'Back', teachers_path %>
<% end %>

</div>
<div>&nbsp;</div>