config/routes.rb
Creditflex::Application.routes.draw do

  resources :interests

  resources :dares

  resources :echos

  resources :badges do
	member do
		get 'assertion'
	end
  end

  resources :challenges do
    member do
	   get 'review'
	   get 'new_from_image'
	   get 'add_image'

	end
	   
	collection do 
		get 'add_image'
		get 'new_from_wish'
		get 'new_from_image'
		post 'icreate'
		end
	end

  resources :wishes do
	member do
		get 'show_challenge'
		get 'share_challenge'
		get 'echo'
		post 'echo'
		get 'confirm_echo'
		post 'confirm_echo'
		get 'tweet'
		post 'tweet'

	end
	collection do 
			get 'add_image'
		end
	end
  resources :comments

  mount Ckeditor::Engine => '/ckeditor'

  resources :responses do
        member do
            post 'new'
		end
	end
  get "sessions/new"
  get "logout" => "sessions#destroy", :as => "logout"
  get "signup" => "users#new", :as => "signup"
  
  resources :users
  resources :sessions

  resources :students

  resources :projects do
        member do
			end
	end
  resources :resources

  resources :users do
			collection do
			
			get 'add_response'
			post 'add_response'
			end	
			
	end		
  resources :teachers 

  resources :portfolios 
		
  resources :requests do
        member do
            post 'new'
			post 'show'
			get 'add_response'
			post 'add_response'
			get 'up_vote'
			post 'up_vote'
			end
		collection do
			
			get 'add_response'
			post 'add_response'
			end	
	end

  resources :proposals do
  collection do 
		get 'add_image'
		get 'new_from_wish'
		get 'new_from_challenge'
		end
  end

  resources :proposal_types

  resources :proposal_statuses

  resources :subjects

  resources :courses do
        member do
            post 'new'
			end
		collection do
			get 'by_subject'
			end	
	end

     match 'lycee' => 'lycee#index'
	 match 'lycee/credits' => 'lycee#credits'
	 match 'lycee/rigor' => 'lycee#rigor'
	 match 'signup_now' => 'users#new'
	 match 'login' => 'users#new'

   root :to => 'wishes#index'

end

app/views/resources/_form.html.erb
<%= form_for(@resource) do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% @resource.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%# f.label :Contributor %><br />
    <%# @resource.user.username %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%# f.text_field :category %>
	<%= f.collection_select :category, Resource::CATEGORIES, :to_s, :humanize %>
  </div>
  <div class="field">
    <%= f.label :county %><br />
    <%= f.text_field :county %>
	<%# f.collection_select :district, Resource::DISTRICTS, :to_s, :humanize %>
  </div>
    <div class="field">
    <%= f.label 'School district' %><br />
    <%= f.text_field :district %>
  </div>
  <div class="field">
    <%= f.label 'URL for resource' %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resources/_ode_guidance.html.erb
<div id="ode_guidance">
<div style="text-align:center"><b>Teachers</b></div><br />
<p>Credit flex isn't about watering down rigor but rather ramping up relevance. This site aims to help teachers and students plan educational experience that of the highest quality.</p>

ODE Guidance Documents
<p>The Ohio Department of Education offers a number of documents about specific subjects and aspects. Check <a href="http://www.education.ohio.gov/GD/Templates/Pages/ODE/ODEDetail.aspx?Page=3&TopicRelationID=1864&ContentID=82751&Content=121092">here</a> or the <a href="http://www.sharedwork.org/group/ohio-credit-flexibility/home1">CF Community of Practice</a> for updates.</p>
<ul>
  <li>World Languages
      <ul>
        <li><a href="http://www.education.ohio.gov/GD/DocumentManagement/DocumentDownload.aspx?DocumentID=90092">Credit Flexibility and World Languages</a> </li>
        <li><a href="http://www.education.ohio.gov/GD/DocumentManagement/DocumentDownload.aspx?DocumentID=67456">Supporting Data - Proficiency and Course Credit</a> </li>
        <li><a href="http://www.education.ohio.gov/GD/DocumentManagement/DocumentDownload.aspx?DocumentID=67542">Language Proficiency</a> </li>
        <li><a href="http://www.education.ohio.gov/GD/DocumentManagement/DocumentDownload.aspx?DocumentID=107446">Frequently Asked Questions</a>&nbsp; </li>
        <li><a href="http://www.education.ohio.gov/GD/DocumentManagement/DocumentDownload.aspx?DocumentID=103416">Existing Credit Flexibility World Languages Program in Ohio</a> </li>
        <li><a href="http://www.education.ohio.gov/GD/DocumentManagement/DocumentDownload.aspx?DocumentID=103417">Stark County Educational Service Center Recommendations</a> </li>
        <li><a href="http://www.education.ohio.gov/GD/DocumentManagement/DocumentDownload.aspx?DocumentID=103415">Jackson Local Credit Flexibility Competency Demonstration</a> </li>
      </ul>
  </li>
  <li>Arts Education (in development) </li>
  <li>Resources for online Educational Options (in development) </li>
  </ul>
<p><strong>Assessment/Gifted Information<br>
</strong></p>
<ul>
  <li><a href="http://www.education.ohio.gov/GD/DocumentManagement/DocumentDownload.aspx?DocumentID=83837">Assessment</a> (3/30/10) </li>
  <li><a href="http://www.education.ohio.gov/GD/DocumentManagement/DocumentDownload.aspx?DocumentID=90986">Advanced Placement Exams</a> (updated 10/15/10) </li>
  <li><a href="http://www.education.ohio.gov/GD/DocumentManagement/DocumentDownload.aspx?DocumentID=82753">Gifted Education</a> (updated 8/20/10) </li>
</ul>
<p><strong>Physical Education/Athletic Eligibility&nbsp;Information</strong></p>
<ul>
  <li><a href="http://www.education.ohio.gov/GD/DocumentManagement/DocumentDownload.aspx?DocumentID=90993">Physical Education</a> (updated 10/15/10) </li>
  <li><a href="http://www.education.ohio.gov/GD/DocumentManagement/DocumentDownload.aspx?DocumentID=92188">NCAA interpretation of &ldquo;nontraditional coursework&rdquo;</a> (10/15/10) </li>
  <li><a href="http://www.education.ohio.gov/GD/DocumentManagement/DocumentDownload.aspx?DocumentID=89446">Athletic Eligibility</a> (6/3/10) </li>
  <li><a href="http://www.education.ohio.gov/GD/Templates/Pages/ODE/ODEDetail.aspx?page=3&amp;TopicRelationID=1793&amp;ContentID=90824&amp;Content=90852" target="_blank">Physical Education and Credit Flexibility</a> (Web page) </li>
</ul>
<p><strong>Career-Technical Information</strong></p>
<ul>
  <li><a href="http://www.education.ohio.gov/GD/DocumentManagement/DocumentDownload.aspx?DocumentID=94032">Career-Tech Credit Flex Presentation</a> (10/29/10) </li>
  <li><a href="http://www.education.ohio.gov/GD/DocumentManagement/DocumentDownload.aspx?DocumentID=89698">Career-Tech Credit Flex</a> (updated 8/23/10) </li>
</ul>
<p><strong>Students with Disabilities</strong></p>
<ul>
  <li><a href="http://www.education.ohio.gov/GD/DocumentManagement/DocumentDownload.aspx?DocumentID=121091">Students with Disabilities</a> (2/10/12) </li>
</ul>

<ul>
    <li>Career/Technical Education
      <ul>
        <li><a href="http://www.education.ohio.gov/GD/DocumentManagement/DocumentDownload.aspx?DocumentID=73645">Academic/CTE credit self-assessment</a> </li>
        <li><a href="http://www.education.ohio.gov/GD/DocumentManagement/DocumentDownload.aspx?DocumentID=73644">Recommendations from ACTE report</a> <em>Reinventing the American High School</em> </li>
      </ul>
    </li>
    <li>Ohio School Boards Association (OSBA)
      <ul>
        <li><a href="http://www.education.ohio.gov/GD/DocumentManagement/DocumentDownload.aspx?DocumentID=73672">Policy guidance</a> (from the OSBA policy manual) </li>
        <li><a href="http://www.education.ohio.gov/GD/DocumentManagement/DocumentDownload.aspx?DocumentID=73671">Featured article on Credit Flexibility</a> (from the July issue of OSBA's <em>PDQ</em>) </li>
      </ul>
    </li>
    <li>Ohio High School Athletics Association (OHSAA)
      <ul>
        <li><a href="http://www.ohsaa.org/eligibility/eligbulletin_09.pdf">Guidance for athletics eligibility</a> (four-page pdf from OHSAA website - see especially page four, checkboxes two and three) </li>
        <li><a href="http://www.education.ohio.gov/GD/DocumentManagement/DocumentDownload.aspx?DocumentID=85394">Credit Flexibility and the OHSAA</a> (PowerPoint) </li>
      </ul>
    </li>
    <li><a href="http://www.getreadyoregon.org/newrequirements.aspx">Oregon State education flexibility policy language</a> </li>
</ul>
</div>

app/views/resources/edit.html.erb
<h1>Editing resource</h1>

<%= render 'form' %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

app/views/resources/index.html.erb
<div id="featured">

<%= image_tag("competition.jpg", {:height => 300}) %>
<div id="feature_graphic">
<div id="main_text">

<%= image_tag("cf_word_map.png", {:height => 280}) %>
</div>

</div>
</div>





<div id="feature_text">
<h1>Why Use Credit Flexibility?  

How?</h1>


<div id="main_text">
<div id="intro">
Get out of class! You can get credit toward high school graduation by <i>doing almost anything.</i></div>
<p>Play the Blues, take a trip, get an internship, do research, start a business, take a class outside school, go to iTunesU, you name it!
</p>
<%= link_to("Is it Rigorous?", "lycee/rigor", :id => "rigor_button") %>
<p class="learn_more">How?<br />
<ul class='learn_more'>
<li><%= link_to 'Explore the ideas here, ask a question', :root  %>.</li>
<li>Talk to your guidance counselor, principal, or teacher. </li>
<li>Visit <a href="http://www.facebook.com/pages/Ohio-Credit-Flexibility/177300152280207">Ohio Credit Flexibility on Facebook</a>.
<li>visit the <a href="http://www.education.ohio.gov/GD/Templates/Pages/ODE/ODEDetail.aspx?page=3&TopicRelationID=1864&ContentID=82751">Credit Flexibility pages</a> at the Ohio Department of Education.</p></p><p></p><p></p>
</ul>

Teachers, parents, others, have something to ask or contribute about the process? 
<ul>
<li>Explore or ask a question at the <a href="http://www.sharedwork.org/group/ohio-credit-flexibility/home1">ODE Community of Practice</a> and get in on the discussion.</li>
<li><%= link_to 'Sign up here as a teacher/mentor', new_teacher_path %></li>
</ul>
</p>

</div>
<iframe id="video" src="http://www.youtube.com/embed/jDxxVABMOOc" frameborder="0" allowfullscreen></iframe>
<% image_tag("students.jpg", {:id => 'photo'}) %>
</div>

<%= render(:partial => 'ode_guidance') %>

<p class="not_ohio">Not in Ohio? Credit Flexibility may be coming to your state!</p>




<h1>Credit Flex Resources</h1>
This area will contain a sortable list of district-by district plans, forms, and other resources.



<% @resources.each do |resource| %>

  <div class='resource'>
    
    Category:<%= resource.category %>&nbsp;&nbsp;<%= link_to 'Link', resource.url %><br />
	<%= resource.district %>
    <p><%= resource.description %></p>
    <%# resource.author_id %><%# resource.viewed %>
	<%= link_to 'more', resource %><br />
	<% if can? :manage, resource %>
		<%= link_to 'Edit', edit_resource_path(resource) %>
		<%= link_to 'Destroy', resource, confirm: 'Are you sure?', method: :delete %></p>
	<% end %>
	</div>

<% end %>


<br />
<% if can? :create, Resource %>
<%= link_to 'New Resource', new_resource_path %>
<% else %>
<%= link_to("Log in", login_path) %> to add a resource.
	<% end %>

app/views/resources/new.html.erb
<h1>New resource</h1>

<%= render 'form' %>

<%= link_to 'Back', resources_path %>

app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Contributor:</b>
  <%= @resource.user.username if @resource.user %>
</p>

<p>
  <b>Category:</b>
  <%= @resource.category %>
</p>
<p>
  <b>County:</b>
  <%= @resource.county %>
</p>
<p>
  <b>District:</b>
  <%= @resource.district %>
</p>
<p>
  <b>Url:</b>
  <%= link_to(@resource.url) %>
</p>

<p>
  <b>Description:</b>
  <%= @resource.description %>
</p>

<p>
  <b>Viewed:</b>
  <%= @resource.viewed %>
</p>


<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>